version: "3"
services:
  db_pigpio:
    restart: always
    image: "postgres:10.3-alpine"
    volumes:
    - /usr/src/DjangoPiGPIO/postgresql:/var/lib/postgresql/data
    env_file:
    - ./.env

  web_pigpio:
    build: .
    restart: always
    env_file:
    - ./.env
    command: "gunicorn --bind 0.0.0.0:8080 DjangoPiGPIO.wsgi"
    volumes:
    - .:/DjangoPiGPIO
    depends_on:
    - db_pigpio

  nginx_pigpio:
    image: "nginx"
    restart: always
    env_file:
    - ./.env
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./staticfiles:/static
    - ./mediafiles:/media
    depends_on:
      - web_pigpio
