# Generated by Django 3.1.2 on 2020-10-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiGPIO', '0018_auto_20190411_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='background_color',
            field=models.CharField(default='#247896', max_length=8, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='col',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=1, verbose_name='Column'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='font_color',
            field=models.CharField(default='#ffffff', max_length=8, verbose_name='Text Color'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='row',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=1, verbose_name='Row'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Description'),
        ),
    ]
